import fs from "node:fs";
import path from "node:path";

const base = path.join(process.cwd(), "packs/_source/elkan5e-magic-items/srd-items-not-finished-converting/wands");

const updates = {
  "wand-of-binding.json": `<p><em>Wand - Rare (Requires Attunement)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). While holding the wand, you can expend charges to cast the following spells (save DC 17):</p><ul><li><p>Action (5 Charges) - <em>@UUID[Compendium.dnd5e.spells24.Item.phbsplHoldMonste]{Hold Monster}</em></p></li><li><p>Action (2 Charges) - <em>@UUID[Compendium.dnd5e.spells24.Item.phbsplHoldPerson]{Hold Person}</em></p></li></ul></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-enemy-detection.json": `<p><em>Wand - Rare (Requires Attunement)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 charge to learn for 1 minute the direction of the nearest creature that is Hostile to you within 60 feet. The wand detects creatures that are Invisible, ethereal, disguised, hidden, or in plain sight. The effect ends if you stop holding the wand.</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-fear.json": `<p><em>Wand - Rare (Requires Attunement)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). While holding the wand, you can expend charges to cast the following spells (save DC 15):</p><ul><li><p>Action (1 Charge) - <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.xwb82OAnypYUZ5BO]{Command}</em> ("flee" or "grovel" only)</p></li><li><p>Action (3 Charges) - <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.GBsOYscOZmOZy0Ff]{Fear}</em> (60-foot Cone)</p></li></ul></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-fireballs.json": `<p><em>Wand - Rare (Requires Attunement by a Spellcaster)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 to 3 charges to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.pbT9cw6nsjpmwrVZ]{Fireball}</em> (save DC 15). The spell is level 3 for 1 charge, and its level increases by 1 for each additional charge expended (maximum of 3 charges per casting).</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-lightning-bolts.json": `<p><em>Wand - Rare (Requires Attunement by a Spellcaster)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 to 3 charges to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.mVhHk4YEzfICiaiz]{Lightning Bolt}</em> (save DC 15). The spell is level 3 for 1 charge, and its level increases by 1 for each additional charge expended (maximum of 3 charges per casting).</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-magic-detection.json": `<p><em>Wand - Uncommon</em></p><p><strong>Activation</strong></p><ul><li><p>3 Charges (Regains 1d3 Charges at Dawn). As an Action you can expend 1 charge to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.zWjDq2YlL1XWOcji]{Detect Magic}</em>.</p></li></ul>`,
  "wand-of-magic-missiles.json": `<p><em>Wand - Uncommon</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 to 3 charges to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.wZJ04LVK8K0jSm1B]{Magic Missile}</em>. The spell is level 1 for 1 charge, and its level increases by 1 for each additional charge expended (maximum of 3 charges per casting).</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-paralysis.json": `<p><em>Wand - Rare (Requires Attunement by a Spellcaster)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 charge to fire a thin blue ray at one creature you can see within 60 feet. The target makes a [[/save CON 15]]{DC 15 Constitution saving throw} or has the &amp;Reference[Paralyzed apply=false] condition for 1 minute. It repeats the save at the end of each of its turns, ending the effect on a success.</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-polymorph.json": `<p><em>Wand - Very Rare (Requires Attunement by a Spellcaster)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 charge to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.wfPXFotkHWY7laah]{Polymorph}</em> (save DC 15).</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-secrets.json": `<p><em>Wand - Uncommon</em></p><p><strong>Activation</strong></p><ul><li><p>3 Charges (Regains 1d3 Charges at Dawn). As an Action you can expend 1 charge; if a secret door or trap is within 60 feet of you, the wand pulses and points toward the closest one.</p></li></ul>`,
  "wand-of-the-war-mage-1-2-or-3.json": `<p><em>Wand - Uncommon (+1), Rare (+2), or Very Rare (+3) (Requires Attunement by a Spellcaster)</em></p><p><strong>Buff</strong></p><ul><li><p>While holding the wand, you gain a +1, +2, or +3 bonus to spell attack rolls based on the wand's rarity, and you ignore &amp;Reference[HalfCover] when making spell attack rolls.</p></li></ul><p>@Embed[Compendium.dnd5e.content24.JournalEntry.dmgFoundryRefere.JournalEntryPage.Ok4iCgD25ENgoRxE cite=false caption=false classes="hide-in-embed"]</p>`,
  "wand-of-web.json": `<p><em>Wand - Uncommon (Requires Attunement by a Spellcaster)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 charge to cast <em>@UUID[Compendium.elkan5e.elkan5e-spells.Item.QbacOEHBdmvlUYl8]{Web}</em> (save DC 13).</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into ashes and is destroyed.</p></li></ul>`,
  "wand-of-wonder.json": `<p><em>Wand - Rare (Requires Attunement)</em></p><p><strong>Activation</strong></p><ul><li><p>7 Charges (Regains 1d6 + 1 Charges at Dawn). As an Action you can expend 1 charge and choose a point within 120 feet. Roll on the Wand of Wonder Effects table to determine the spell or magical effect originating from that point (save DC 15). If a spell normally has a range less than 120 feet, it instead has a range of 120 feet when cast from the wand. When an effect has multiple potential targets, the GM determines the subjects randomly.</p></li><li><p>If you expend the wand's last charge, roll [[/r 1d20]]. On a 1, the wand crumbles into dust and is destroyed.</p></li></ul><details><summary>Wand of Wonder Effects Table</summary><p>@Embed[Compendium.dnd5e.tables24.RollTable.dmgWandOfWonderE rollable caption=false]</p></details><section id="foundry-secret-1" class="secret"><p><strong>Foundry Note</strong></p><p>The actionable effects of the table are included as activities and implemented as much as possible in the table to provide flexibility in how you'd like to use them.</p><p>The <strong>Expend</strong> activity should be used for any effect which isn't implemented as an activity for tracking charge uses.</p></section>`
};

let updated = 0;

for (const [file, value] of Object.entries(updates)) {
  const filePath = path.join(base, file);
  const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
  if (data?.system?.description?.value === value) continue;
  data.system.description.value = value;
  fs.writeFileSync(filePath, JSON.stringify(data, null, "\t") + "\n");
  updated++;
}

console.log(`Updated descriptions for ${updated} wands.`);
